plugins: rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.4

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

